version: '3'

services: 
  pgsql:
    image: 'postgres:11'
    ports:
      - "5432:5432"
    environment:
      - "PG_USER=postgres"
      - "PG_PASS=pass1234"
      - "PG_DB=dbName"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
